 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
```{r load-packages, include=FALSE}
library(tidyverse)
library(broom)
library(car)
library(ggplot2)
library(lmtest)
library(glmnet)
library(ggplot2)
library(caret)
library(boot)
library(haven)
```


```{r}
w6 <- read_dta("w6.dta")
cat("dimensions of the data frame:",dim(w6))

```



```{r}
head(w6)
```


```{r}
  
 
relations <-  c("cp6ylpcg", "cp6mrelf",   "p6e1", "cp6hhsize", "p6d24", "p6d25", "k6c6a", "k6c6b", "k6c7c", "p6d28", "p6d29", "k6c9c", "k6c9d", "p6d31", "k6d36b", "p6d32", "p6d33", "p6d34", "p6d35", "p6d36", "p6d37", "p6d39", "p6e38", "p6e39", "p6f1", "p6f2", "p6f11", "p6f22", "k6c10", "k6c21", "k6c17", "k6c28", "k6c33", "k6c37", "p6f32", "p6f35", "p6g9", "p6g11", "p6g17", "p6g23", "k6c00aa", "k6c00ab", "k6c00ac", "k6c00ad", "k6c00ak", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c9f", "k6c46", "k6c47", "k6d35b", "k6d46", "k6d57", "k6d59", "k6f1a", "k6f1b" , "p6b35", "p6b37", "p6b39", "p6b38", "p6b41", "p6b42", "p6b45", "p6b49", "p6d21a", "k6b1a", "k6b29", "k6b30", "k6d1b", "k6d1d", "k6d1e", "k6d1f", "k6d1i", "k6d1j", "k6d1k", "k6d2g", "k6d2l", "k6d2y", "k6d36d", "k6d62a", "k6d62b", "k6d62c", "k6d62g", "k6d64", "k6f4", "k6f14" , "p6b51" , "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e10", "k6e12", "k6e18", "k6e36" , "p6h78", "p6h79", "p6h80", "p6h86", "k6d40", "k6d42", "k6d44", "k6d48", "k6d55", "k6f63", "p6h75", "p6h76", "p6h79", "p6h87a" ,"p6i3", "p6i4", "p6i5", "p6i7", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6j11" )

social <- w6[relations]
social <- social[!duplicated(names(social)) | !names(social) %in% relations]

cat("dimensions of the social related data:",dim(social))
```
 
```{r}
  social <- subset(social, !apply(social, 1, function(x) any(x ==-9 | x==-7)))
  cat("dimensions of the filtered social related data:",dim(social))
```

```{r}
dmy <- dummyVars(" ~ .", data = social)
social <- data.frame(predict(dmy, newdata = social))


```



```{r}
social$p6i3
```

```{r}

cor(social[c("p6i3", "p6i4", "p6i5", "p6i7")])

```

3~4~5 -> 4
```{r}
 

cor(social[c("k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14")])

```
 
```{r}
head(social$k6d40)
```
```{r}
social$k6d40
summary(social$k6d40)
summary(social$k6d42)
```
```{r}

social$cig_num <- ifelse(social$k6d40 == 2, 0, ifelse(social$k6d40 == 1, social$k6d42, social$k6d40))
summary(social$cig_num)
social$cig_num

```



```{r}
head(social$k6e10)
```
```{r}
summary(social$k6e12)
```
 
```{r}
social$police_stop_num <- ifelse(social$k6e10 == 2, 0, ifelse(social$k6e10 == 1, social$k6e12, social$k6e10))
summary(social$police_stop_num)
```
```{r}
social$suspend_num <- ifelse(social$k6b29 == 2, 0, ifelse(social$k6b29 == 1, social$k6b30, social$k6b29))
summary(social$suspend_num)
```


```{r}
cor(social[c( "cp6mrelf", "cp6prelb", "cp6pmarb", "p6e1")])
```
"cp6mrelf", "cp6prelb", "cp6pmarb" -> cp6mrelf
```{r}
cor(social[c(  "p6d24", "p6d25", "k6c6a", "k6c6b", "k6c7c")])
```
```{r}
cor(social[c( "p6d28", "p6d29", "k6c9c", "k6c9d")])
```
 
```{r}
cor(social[c("p6d32", "p6d33", "p6d34", "p6d35", "p6d36")])
```
 
```{r}
cor(social[c( "p6f1", "p6f2", "p6f11", "p6f22", "k6c10", "k6c21", "k6c17", "k6c28", "k6c33", "k6c37")])
```
 p6f2 , p6f22 , k6c21 -> p6f22
```{r}
#A1
library(caret)
A1_vars <- c("k6f63", "p6h78", "p6h79", "p6h80", "p6h86", "k6d40", "k6d42", "k6d44", "k6d48", "k6d55", "p6h75", "p6h76",   "p6h87a", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b49", "p6d21a", "k6b1a", "k6d1f", "k6d1j", "k6d2g", "k6d2l", "k6d2y", "k6d62a", "k6d62c", "k6d64", "cp6ylpcg", "cp6mrelf",   "p6e1", "p6d24", "p6d25", "k6c6a", "k6c6b", "p6d39", "p6f32", "p6g9", "k6c4b", "k6c4e", "k6c46", "k6c47", "k6d46", "k6d57", "k6d59")
A1  <- social[,unique(A1_vars)]
```
 
 
```{r}
#A2
A2_vars <- c("cig_num", "k6f63", "p6h78", "p6h79", "p6h80", "p6h86", "k6d44", "k6d48", "k6d55", "p6h75", "p6h76", "p6h79", "p6h87a", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b49", "p6d21a", "k6b1a", "k6d1f", "k6d1j", "k6d2g", "k6d2l", "k6d2y", "k6d62a", "k6d62c", "k6d64", "cp6ylpcg", "cp6mrelf",   "p6e1", "p6d24", "p6d25", "k6c6a", "k6c6b", "p6d39", "p6f32", "p6g9", "k6c4b", "k6c4e", "k6c46", "k6c47", "k6d46", "k6d57", "k6d59")
A2  <- social[,unique(A2_vars)]
```
 
 
 
```{r}
#A3
A3_vars <- c("k6d55", "p6h78", "p6h79", "p6h80", "p6h86", "k6d40", "k6d42", "k6d44",  "k6f63", "p6h75", "p6h76", "p6h79", "p6h87a", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b49", "p6d21a", "k6b1a", "k6d1f", "k6d1j", "k6d2g", "k6d2l", "k6d2y", "k6d62a", "k6d62c", "k6d64", "cp6ylpcg", "cp6mrelf",     "p6e1", "p6d24", "p6d25", "k6c6a", "k6c6b", "p6d39", "p6f32", "p6g9", "k6c4b", "k6c4e", "k6c46", "k6c47", "k6d46", "k6d57", "k6d59")
A3 <- social[,unique(A3_vars)]
```
 
 
 
```{r}
B1_vars <- c("police_stop_num", "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e18", "k6e36", "p6h86", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b35", "p6b37", "p6b39", "p6b38", "p6b41", "p6b42", "p6b45", "p6b49", "k6d62g", "cp6ylpcg", "cp6mrelf",   "p6e1", "p6d24", "p6d29", "k6c9c", "k6c9d", "p6f1",  "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33", "k6c37", "p6f35", "p6g11", "p6g17", "p6g23", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c46", "k6c47")
B1 <- social[,unique(B1_vars)]
```
 
 
 
```{r}
B2_vars <- c("suspend_num", "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e18", "k6e36", "p6h86", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6b35", "p6b37", "p6b39", "p6b38", "p6b41", "p6b42", "p6b45", "p6b49", "k6d62g", "cp6ylpcg", "cp6mrelf",  "p6e1", "p6d24", "p6d29", "k6c9c", "k6c9d", "p6f1",  "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33", "k6c37", "p6f35", "p6g11", "p6g17", "p6g23", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c46", "k6c47","k6d55"   )
B2 <- social[,unique(B2_vars)]
```
 
```{r}
B3_vars <- c("k6e36", "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e18", "p6h86", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6b35", "p6b37", "p6b39", "p6b38", "p6b41", "p6b42", "p6b45", "p6b49", "k6d62g", "cp6ylpcg", "cp6mrelf",   "p6e1", "p6d24", "p6d29", "k6c9c", "k6c9d", "p6f1",   "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33",   "p6f35", "p6g11", "p6g17", "p6g23", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c46", "k6c47")
B3 <- social[,unique(B3_vars)]
```
 
 
```{r}
B4_vars <- c("p6b41", "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e18", "p6h86", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b35", "p6b37", "p6b39", "p6b38", "p6b45", "p6b49", "k6d62g", "cp6ylpcg", "cp6mrelf",  "p6e1", "p6d24", "p6d29", "k6c9c", "k6c9d", "p6f1",   "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33", "k6c37", "p6f35", "p6g11", "p6g17", "p6g23", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c46", "k6c47")
B4 <- social[,unique(B4_vars)]
```
 
 
```{r}
B5_vars <- c("p6b42", "p6h102", "k6d61b", "k6d61c", "k6d61d", "k6e5", "k6e6", "k6e7e", "k6e7f", "k6e18", "p6h86", "k6e4b", "k6e4c", "p6i11", "p6i12", "p6i13", "p6i14", "p6b35", "p6b37", "p6b39", "p6b38", "p6b45", "p6b49", "k6d62g", "cp6ylpcg", "cp6mrelf",  "p6e1", "p6d24", "p6d29", "k6c9c", "k6c9d", "p6f1",   "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33", "k6c37", "p6f35", "p6g11", "p6g17", "p6g23", "k6c3", "k6c4b", "k6c4e", "k6c9a", "k6c46", "k6c47")
B5 <- social[,unique(B5_vars)]
```
 
 
 
```{r}
C1_vars <- c("p6b51", "p6h102", "k6d61b", "k6d61c", "k6e7f", "p6b35", "p6b37", "p6b39", "p6b38", "p6b49", "k6d1b", "k6d1f", "k6d2l", "p6d37", "p6e38", "p6e39", "p6f1",   "p6f11", "p6f22", "k6c10",  "k6c17", "k6c28", "k6c33", "k6c37", "p6g11", "p6g17", "k6c4b", "k6c4e", "k6c46", "k6c47")
C1 <- social[,unique(C1_vars)]

```
 
 
```{r}
D1_vars <- c("k6f14", "p6b35", "p6b49", "p6d21a", "k6b1a", "k6d1d", "k6d1e", "k6d1f", "k6d1i", "k6d1j", "k6d1k", "k6d2g", "k6d2l", "k6d2y", "k6d36d", "k6d64", "cp6ylpcg", "cp6mrelf",   "p6e1", "cp6hhsize", "k6c7c", "p6d28", "p6d29", "k6c9c", "k6c9d", "p6d31", "k6d36b", "p6d37", "p6e38", "p6e39", "p6f1",   "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33",  "k6c3", "k6c4b", "k6c4e", "k6c9f", "k6c46", "k6c47", "k6d35b", "k6f1a", "k6f1b")
D1 <- social[,unique(D1_vars)]
```
 
 
```{r}
D2_vars <- c("k6d1j", "p6b35", "k6f4", "p6b49", "p6d21a", "k6b1a", "k6d1d", "k6d1e", "k6d1f", "k6d1i", "k6f14", "k6d1k", "k6d2g", "k6d2l", "k6d2y", "k6d36d", "k6d64", "cp6ylpcg", "cp6mrelf",   "p6e1", "cp6hhsize", "k6c7c", "p6d28", "p6d29", "k6c9c", "k6c9d", "p6d31", "k6d36b", "p6d37", "p6e38", "p6e39", "p6f1",   "p6f11", "p6f22", "k6c10",   "k6c17", "k6c28", "k6c33", "k6c37", "k6c3", "k6c4b", "k6c4e", "k6c9f", "k6c46", "k6c47", "k6d35b", "k6f1a", "k6f1b")
D2 <- social[,unique(D2_vars)]
```
 
 
```{r}
library(ggplot2)
 his1 <- B1
 his1$police_stop_num[his1$police_stop_num<0]<-0
ggplot(his1, aes(x = police_stop_num)) +
      geom_histogram(
          binwidth = 1,
          fill = "red", color = "yellow",  alpha = 0.6) +
   
  scale_y_continuous(trans = "log10") +
      labs(
          title = "Distribution of the times stopped by the police",
          x = "Number of times stopped by the police", y = "Frequency" ) +
       theme(
          plot.title = element_text( hjust = 0.5, size = 16, face = "bold"  ),
          axis.title.x = element_text(  size = 14, face = "bold"  ),
          axis.title.y = element_text(  size = 14, face = "bold" ),   
          panel.grid.minor = element_line(color = "gray", linewidth = 0.5)) 
```
 


```{r}
 his2 <- B1
 head(B1)
 his2$police_stop_num[his2$police_stop_num<0]<- 0
 his2$k6c4e  [his2$k6c4e  <0]<- NA
 his2$k6c4e <- ifelse(his2$k6c4e  == 1 , "Zoo!",ifelse(his2$k6c4e  == 2 , "Moderate",ifelse(his2$k6c4e  == 3 , "Calm", "NA")) )
 his2$k6d55_fac <- as.factor(his2$k6c4e  )
ggplot(his2, aes(x = police_stop_num, fill = k6d55_fac           )) +
      geom_histogram(
          binwidth = 1,
           alpha = 0.6) +
    
      labs(
          title = "Distribution of the times stopped by police",
          x = "Number of Times youth stopped by police", y = "Frequency" ,
          fill = "home atmosphere") +
  scale_y_continuous(trans = "log10") +
       theme(
          plot.title = element_text( hjust = 0.5, size = 16, face = "bold"  ),
          axis.title.x = element_text(  size = 14, face = "bold"  ),
          axis.title.y = element_text(  size = 14, face = "bold" ),   
          panel.grid.minor = element_line(color = "gray", linewidth = 0.5)) 
```
 
 
```{r}
 his2 <- B2

 his2$suspend_num[his2$suspend_num<0]<- 0
 his2$k6d55[his2$k6d55<0]<- 1
 his2$k6d55_fac <- as.factor(his2$k6d55)
ggplot(his2, aes(x = suspend_num, fill = k6d55_fac     , color=k6d55_fac     )) +
      geom_histogram(
          binwidth = 1,
           alpha = 0.6) +
   
  scale_y_continuous(trans = "log10") +
      labs(
          title = "Distribution of the times suspended",
          x = "Number of Times suspended or expelled in past 2 years", y = "Frequency" ) +
       theme(
          plot.title = element_text( hjust = 0.5, size = 16, face = "bold"  ),
          axis.title.x = element_text(  size = 14, face = "bold"  ),
          axis.title.y = element_text(  size = 14, face = "bold" ),   
          panel.grid.minor = element_line(color = "gray", linewidth = 0.5)) 
```

 
 
```{r}


box1 <- social


box1$parents <- ifelse(social$cp6mrelf == 1 | social$cp6mrelf == 2| social$cp6mrelf == 6, "together", 
                        ifelse(social$cp6mrelf < 1, "None",  "separated")) 

box1$parents <- as.factor(box1$parents)
box1$ethinity <- ifelse(social$k6c00aa == 1, "White  ", 
                        ifelse(social$k6c00ab == 1, " Black ", 
                              
                                             ifelse(social$k6c00ak == 1, " Mixed" , "None")))
box1$ethinity  <- as.factor(box1$ethinity)
box1$stopped_by_police <- social$police_stop_num
neg_box1 <- which(box1$stopped_by_police < 0)
box1  <- box1[ - neg_box1,]
 box1  <- box1[ - which(box1$parents ==  "None") ,]
ggplot(box1 , aes(x= ethinity , y= stopped_by_police, fill = parents )) + geom_boxplot() +  
  labs( title = "crime of different ethinities and parents relation  ",
    x = "Ethinity",
    y = " Times stopped by Police" ) +  
   
  scale_y_continuous(trans = "log10")+
  theme(
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold" ) )
        
        
```
 
 
```{r}
summary(B3$k6e36 )
```

```{r}
neg_B3 <- which(B3$k6e36 < 0)
B3  <- B3[ - neg_B3,]
summary(B3$k6e36)
```


```{r}
B3$k6e36 <- -1 * B3$k6e36 +2 
summary(B3$k6e36)

```
  
 
 
```{r}
B3$k6e36 <- as.factor(B3$k6e36)
B3_model <- glm( k6e36 ~ ., data = B3 , family = "binomial")
B3_kfold <- train( k6e36 ~ ., data = B3, family = "binomial",
                  method="glm",  trControl = trainControl(method = "cv", number = 5))
pvalues_B3 <- summary(B3_model )$coefficients[, "Pr(>|z|)"]
B3_kfold_sig <- train( k6e36 ~ . , data = B3[, c("k6e36", names(pvalues_B3[pvalues < 0.05]))], family = "binomial",
                  method="glm", trControl = trainControl(method = "cv", number = 5))
 data.frame( Model = c("all parameters", "significant parameters"  ),
            accuracy = c( B3_kfold $results$Accuracy, B3_kfold_sig$results$Accuracy),
            predictors = c( length(predictors(B3_kfold )), length(predictors(B3_kfold_sig)))) 
```
 
 
```{r}
pred_probs_B3 <- predict(B3_model, type="response")
calib_data_B3 <- data.frame(prob = pred_probs_B3, bin = cut(pred_probs_B3, breaks = num_cuts),class = B3_model$y)
calib_data_B3 <- calib_data_B3 %>%
group_by(bin) %>%
summarize(observed = sum(class)/n(),
expected = sum(prob)/n(),
se = sqrt(observed*(1-observed)/n()))
ggplot(calib_data_B3) +
geom_abline(intercept = 0, slope = 1, color="red") +
geom_errorbar(aes(x = expected, ymin=observed-1.96*se,
ymax=observed+1.96*se),
colour="black", width=.01)+
geom_point(aes(x = expected, y = observed)) +
labs(x="Expected Proportion", y="Observed Proportion") +
theme_minimal()
```
 
```{r}
summary(B3_kfold_sig)
```  
  
 
